### ISSUE TITLE
[low] Syntax error in print

### ISSUE THREAD

**Issue by DDzwiedziu** [mewfree/youtube-dl-subscriptions#1]
$ youtube-dl-subscryptions.py 
      File "youtube-dl-subscryptions.py", line 35
        print('Parsing through channel '+str(i+1)+' out of '+str(len(urls)), end='\r')
                                                                                ^
    SyntaxError: invalid syntax

**Comment by mewfree** [comment]
@DDzwiedziu This is Python 3 code, looks like you're running it under a Python 2 interpreter
