### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by agarrharr** [mewfree/youtube-dl-subscriptions#5]
I got the following error:

```sh
❯ python dl.py
  File "dl.py", line 33
    print('Parsing through channel '+str(i+1)+' out of '+str(len(urls)), end='\r')
                                                                            ^
SyntaxError: invalid syntax
```

**Comment by mewfree** [comment]
@agarrharr This is Python 3 code, looks like you're running it under a Python 2 interpreter

**Comment by TomasHubelbauer** [comment]
@mewfree Maybe something like [a runtime version check](https://stackoverflow.com/a/9079062/2715716) would help. I can try and PR if you think it's worthwhile.

**Comment by mewfree** [comment]
@TomasHubelbauer as you wish! I could also just edit the README to mention it's Python 3 code
